version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '12:00'
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      time: '12:00'
    groups:
      python:
        patterns:
          - "*"
