language: python
python:
  - "3.6"
os:
  - linux
#  - osx
sudo: false
install:
  # Python 3.x is default
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Prepare env with Python version
  - conda create -n finch python=$TRAVIS_PYTHON_VERSION
  # Update now the env with our environment
  - conda env update -f environment.yml
  - source activate finch
  # Packages for testing
  - conda install pytest flake8
  - pip install --no-deps -e .
  - pip install flufl.enum pathlib
before_script:
  # Start WPS service on port 5000 on 0.0.0.0
  - make start
  - sleep 2
script:
  - pytest -m "not online"
  - flake8
