dist: xenial # required for Python >= 3.7
language: python
python:
  - "3.7"
  - "3.8"
os:
  - linux
sudo: false
install:
  # Python 3.x is default
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install setuptools
  - conda update -q conda
  - conda create -n finch -c conda-forge python=$TRAVIS_PYTHON_VERSION
  - conda env update -f environment.yml
  - source activate finch
  # Packages for testing
  - conda install -c conda-forge pytest flake8 birdy nbval
  - python setup.py install
before_script:
  # Start WPS service on port 5000 on 0.0.0.0
  - make start
  - sleep 2
script:
  - pytest -m "not online" tests
  - FINCH_WPS_URL=http://localhost:5000 make test-notebooks
  - flake8
