name: finch
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.14
  - birdy >=0.8.1
  - ipython >=8.5.0
  - matplotlib-base >=3.5.0
  - nbsphinx >=0.9.8
  - sphinx >=7.0.0
  - sphinxcontrib-bibtex >=2.6.0
