# WARNING:
#   This enviroment definition should only contain packages required by Finch directly.
#   For dev,docs or other support dependencies, refer to the relevant pyproject groups.
#   This is important to keep the Docker image size small.
name: finch
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.15
  - pip >=26.1.0
  - anyascii >=0.3.0
  - cftime >=1.4.1
  - cf_xarray >=0.9.3
  - click >=8.1.7
  - clisops >=0.16.2
  - dask >=2023.5.1
  - distributed
  - geopandas >=1.0
  - jinja2 >=3.1.4
  - netcdf4
  - numpy >=1.25.0
  - pandas >=2.2.0,<3.0
  - parse >=1.20
  - psutil >=6.0.0
  - python-slugify >=8.0
  - pywps >=4.6
  - pyyaml >=6.0.1
  - scipy >=1.9.0
  - sentry-sdk
  - setuptools >=78.1.1
  - siphon >=0.10.0
  - werkzeug >=3.0.6
  - xarray >=2023.11.0
  - xclim >=0.61,<0.62 # remember to match xclim version in pyproject.toml as well
  - xesmf >=0.8.2,!=0.8.8
  - xsdba =0.6.1   # remember to match xsdba version in pyproject.toml as well
  - xscen >=0.15,<0.16  # remember to match xscen version in pyproject.toml as well
  # Temporary fixes
  - fastprogress <1.1  # FIXME: Temporary fix following https://github.com/intake/intake-esm/pull/773. Remove when intake-esm is updated in xscen.
