name: Conditional Bump Version

on:
  push:
    branches:
      - master
    paths-ignore:
      - .*
      - .github/*/*.md
      - .github/*/*.yml
      - AUTHORS.rst
      - CHANGES.rst
      - CI/*.in
      - CI/*.txt
      - Dockerfile
      - Makefile
      - docker-compose.yml
      - docs/*/*.ipynb
      - docs/*/*.py
      - docs/*/*.rst
      - docs/Makefile
      - docs/_static/*
      - environment.yml
      - environment-docs.yml
      - finch/__version__.py
      - requirements*.txt
      - setup.cfg
      - setup.py

permissions:
  contents: read

jobs:
  bump_patch_version:
    name: Bumpversion
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
      - name: Generate App Token
        id: token_generator
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # v1.10.4
        with:
          app-id: ${{ secrets.BIRDHOUSE_HELPER_BOT_ID }}
          private-key: ${{ secrets.BIRDHOUSE_HELPER_BOT_KEY }}
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.token_generator.outputs.token }}
      - name: Set up Python3
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: "3.x"
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ secrets.BIRDHOUSE_HELPER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BIRDHOUSE_HELPER_BOT_GPG_PRIVATE_KEY_PASSWORD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          trust_level: 5
      - name: Current Version
        run: |
          CURRENT_VERSION="$(grep -E '__version__' finch/__version__.py | cut -d ' ' -f3)"
          echo "current_version=${CURRENT_VERSION}"
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Install CI libraries
        run: |
          python -m pip install -r --require-hashes CI/requirements_ci.txt
      - name: Conditional Bump
        run: |
          if [[ ${{ env.CURRENT_VERSION }} =~ -dev(\.\d+)? ]]; then
            echo "Development version (ends in 'dev(\.\d+)?'), bumping 'build' version"
            bump-my-version bump build
          else
            echo "Version is stable, bumping 'patch' version"
            bump-my-version bump patch
          fi
          NEW_VERSION="$(grep -E '__version__' finch/__version__.py | cut -d ' ' -f3)"
          echo "new_version=${NEW_VERSION}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
      - name: Push Changes
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          force: false
          branch: ${{ github.ref }}
